# Generated by Django 4.1.2 on 2022-12-20 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subcategory')),
            ],
        ),
    ]
