# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-22 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(0, 'E'), (1, 'I'), (2, 'T')]),
        ),
    ]
