# Generated by Django 4.1.2 on 2022-10-27 10:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('group_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.wallet')),
                ('loaned_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_set_loaned_by_me', to=settings.AUTH_USER_MODEL)),
                ('loaned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_set_loaned_to_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
