# Generated by Django 4.1.2 on 2022-12-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupwalletrecord',
            name='record_type',
            field=models.IntegerField(choices=[(0, 'Expense'), (1, 'Income'), (2, 'Transfer')], default=0),
            preserve_default=False,
        ),
    ]
