# Generated by Django 4.1.2 on 2022-12-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_tag'),
        ('finances', '0004_alter_groupwalletrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupwalletrecord',
            name='tags',
            field=models.ManyToManyField(to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='personalwalletrecord',
            name='tags',
            field=models.ManyToManyField(to='catalog.tag'),
        ),
    ]
