# Generated by Django 4.1.1 on 2022-10-07 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('catalog', '0001_initial'),
        ('finances', '0005_transform_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spendinggroup',
            name='users',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.subcategory'),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user'),
        ),
        migrations.AlterField(
            model_name='spendinggrouprecord',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.spendinggroup'),
        ),
        migrations.AlterField(
            model_name='spendinggrouprecord',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_by_me_set', to='authorization.user'),
        ),
        migrations.AlterField(
            model_name='spendinggrouprecord',
            name='paid_for_users',
            field=models.ManyToManyField(related_name='paid_for_me_set', to='authorization.user'),
        ),
        migrations.AlterField(
            model_name='spendinggrouprecord',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.subcategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SpendingGroup',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
